# Generated by Django 2.2.1 on 2019-07-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='Slides/'),
        ),
    ]
