# Generated by Django 2.2.1 on 2019-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='image',
        ),
        migrations.AddField(
            model_name='comic',
            name='tags',
            field=models.ManyToManyField(to='comics.Tag', verbose_name='comic-tags'),
        ),
    ]
