# Generated by Django 2.2 on 2019-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_comic_views_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='cover',
            field=models.ImageField(blank=True, default='no-image.png', upload_to=''),
        ),
    ]
