# Generated by Django 2.2.1 on 2019-06-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20190626_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='orderNumber',
            field=models.SmallIntegerField(default=0, unique=True, verbose_name='Order Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comics.Comic'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Hyperlink'),
        ),
    ]
