# Generated by Django 2.2.1 on 2019-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20190724_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='default_display_style',
            field=models.CharField(choices=[('M', 'Manga Style'), ('W', 'Webtoon Style')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('H', 'On Hold'), ('D', 'Dropped'), ('I', 'Inactive')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='comic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='comics.Tag', verbose_name='Tags'),
        ),
    ]
