# Generated by Django 2.2.1 on 2019-08-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_slide_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='blog',
            new_name='blog_post',
        ),
    ]
