# Generated by Django 2.2.1 on 2019-08-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_auto_20190801_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='discord_role_id',
            field=models.CharField(default='606207001588006978', max_length=40, verbose_name='Discord Role Id'),
            preserve_default=False,
        ),
    ]
