# Generated by Django 2.2.1 on 2019-08-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_comic_discord_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('H', 'On Hold'), ('D', 'Dropped'), ('I', 'Inactive'), ('C', 'Completed')], default='W', max_length=1),
        ),
    ]
